In [54]:
# PERFORM LU DECOMPOSTION OF SQUARE MATRIX A
import numpy as np
import scipy.linalg as lg  #Scipy linear Algebra Library
A= np.array([[4,-2,-3,1],[1,3,1,3],[1,2,-1,-2],[2,1,-1,-1]])
print('A: ')
print(A)


P,L,U =lg.lu(A) # where P is unit matrix. here decomposed matrix A into lower triangular matrix(L) and UPPEr TRIANGULAR matrix(U)
print("P: ") # A=LU
print(P)
print('L: ')
print(L)
print('U: ')
print(U)
np.allclose(L@U,A) # show A=PLU

A: 
[[ 4 -2 -3  1]
 [ 1  3  1  3]
 [ 1  2 -1 -2]
 [ 2  1 -1 -1]]
P: 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
L: 
[[1.         0.         0.         0.        ]
 [0.25       1.         0.         0.        ]
 [0.25       0.71428571 1.         0.        ]
 [0.5        0.57142857 0.33333333 1.        ]]
U: 
[[ 4.         -2.         -3.          1.        ]
 [ 0.          3.5         1.75        2.75      ]
 [ 0.          0.         -1.5        -4.21428571]
 [ 0.          0.          0.         -1.66666667]]


True

In [55]:
# Solve the equation Ax=B BY USING LU FACTORIZATION
import numpy as np
import scipy.linalg as lg 
A= np.array([[4,-2,-3,1],[1,3,1,3],[1,2,-1,-2],[2,1,-1,-1]])
B=np.array([[20],[14],[3],[9]])
print('B')
print(B)
LU,y=lg.lu_factor(A) # Do the factorization

X= lg.lu_solve((LU,y),B) #solve the system
print('X')
print(X)



B
[[20]
 [14]
 [ 3]
 [ 9]]
X
[[ 5.]
 [ 1.]
 [-0.]
 [ 2.]]


In [56]:
# GAUSSIAN ELIMINATION
# 4x1-2x2-3x3-x4=20
# x1+3x2+x3+3x4=14    
# x1+2x2-x3-2x4=3
# 2x2+x2-x3-x4=9

In [57]:
# input system ofequatins
A=np.array([[4,-2,-3,1],[1,3,1,3],[1,2,-1,-2],[2,1,-1,-1]],float)
B=np.array([[20],[14],[3],[9]],float)
print('A')
print(A)
print('B') # AX=B
print(B)

A
[[ 4. -2. -3.  1.]
 [ 1.  3.  1.  3.]
 [ 1.  2. -1. -2.]
 [ 2.  1. -1. -1.]]
B
[[20.]
 [14.]
 [ 3.]
 [ 9.]]


In [58]:
n=len(B)
X=np.zeros(n,float)


In [59]:
# Forward Elimination
for k in range(n-1):
    for i in range(k+1,n):
        fctr=A[i,k] / A[k,k]
        for j in range(k,n):
            A[i,j]=A[i,j]-fctr*A[k,j]
        B[i]=B[i]-fctr*B[k]

        
# Back-substitution 
X[n-1]=B[n-1] / A[n-1,n-1]
for i in range(n-2,-1,-1):
    Sum =B[i]
    for j in range(i+1,n):
        Sum=Sum- A[i,j]*X[j]
    X[i]= Sum/A[i,i]

  # CHECK WHETHER THERE ARE 0,1 AND INFINTELY MANY SOLUTIONS:  
print('the sulution of the system:')
print(X)

# CHECK WHETHER THERE ARE 0,1 AND INFINTELY MANY SOLUTIONS:
rank_A=np.linalg.matrix_rank(A)
print('rank_A:',rank_A)
aug_A=np.array([[4,-2,-3,1,20],[1,3,1,3,14],[1,2,-1,-2,3],[2,1,-1,-1,9]],float) 
print('aug_A')
print(aug_A)
rank_aug_A=np.linalg.matrix_rank(aug_A)
print('rank_aug_A')
print(rank_aug_A)
if (rank_A==rank_aug_A)&(rank_aug_A==np.shape(A)[0]):
    print("The system has a unique solution. \n")
elif (rank_A==rank_aug_A)&(rank_aug_A<np.shape(A)[0]):
      print("The system has many solution \n")
if(rank_A<rank_aug_A):
      print("The system is inconsistent.")
      

the sulution of the system:
[ 5.  1. -0.  2.]
rank_A: 4
aug_A
[[ 4. -2. -3.  1. 20.]
 [ 1.  3.  1.  3. 14.]
 [ 1.  2. -1. -2.  3.]
 [ 2.  1. -1. -1.  9.]]
rank_aug_A
4
The system has a unique solution. 



In [60]:
# read the matrix A from csv file and read the vector from csv file 
import pandas as pd # oandas is python libraray it is used for working with data sets i.e cleaning,manipulating data
A=pd.read_csv("pythonmatrixA.csv") # read csv file using read_csv() method defined in pandas library
B=pd.read_csv("pythonvectorB.csv")
A=A.to_numpy()
B=B.to_numpy()
print('A:')
print(A)
print('B:')
print(B)


A:
[[23 34 12  5  8]
 [21 32  3  7 41]
 [ 8  9 32  9  0]
 [ 3 12 22 24 27]]
B:
[[23]
 [45]
 [34]
 [33]]


In [61]:
# Diagonalization of matrix 
import numpy as np
A=np.array([[3,-3,9],[-3,11,3],[9,3,3]])
eigenvalues,eigenvectors = np.linalg.eig(A)
P= eigenvectors
B=A.transpose() # Transpose of given array

if np.array_equal(A,B):#compare arrays using array_equal() method
    print("matrix is symmetric")
D = np.zeros((3,3))
for i in range(3):
    D[i,i]= eigenvalues[i]
P_inv= np.linalg.inv(P)
print('P:')
print(P) # eigensvectors matrix 
print('D:')
print(D)
print('P_inv:') # inverse of eigensvector matrix
print(P_inv)    
d=P.dot(D.dot(P_inv))
print("verify result:")# it is for verifying result 
print(d)

print('eigenvalues:')   
    
print(eigenvalues)# for eigensvalues pairs 
        

    
    

matrix is symmetric
P:
[[ 0.72547625 -0.6882472  -0.01800032]
 [-0.21764288 -0.22941573  0.95379133]
 [ 0.65292863  0.6882472   0.29993013]]
D:
[[12.  0.  0.]
 [ 0. -7.  0.]
 [ 0.  0. 12.]]
P_inv:
[[ 0.72547625 -0.19409716  0.6607772 ]
 [-0.6882472  -0.22941573  0.6882472 ]
 [ 0.          0.94897545  0.31632515]]
verify result:
[[ 3. -3.  9.]
 [-3. 11.  3.]
 [ 9.  3.  3.]]
eigenvalues:
[12. -7. 12.]


In [62]:
# Find all eigenspairs of matrix
A=np.array([[2,2,4],[1,3,5],[2,3,4]])
W,V=np.linalg.eig(A) # W=eigens_values and V =eigens_vectors
print('eigens pair:',W,"\n",V)



eigens pair: [ 8.80916362  0.92620912 -0.73537273] 
 [[-0.52799324 -0.77557092 -0.36272811]
 [-0.604391    0.62277013 -0.7103262 ]
 [-0.59660259 -0.10318482  0.60321224]]


In [63]:
# Give the exponential function on matrix A 
import numpy as np
A=np.array([[1,3,4],[2,6,6],[3,8,2]])
print("A: ")
print(A)
e=np.exp(A) # calculate the exponential
print("exponetial of A: ")
print(e)



A: 
[[1 3 4]
 [2 6 6]
 [3 8 2]]
exponetial of A: 
[[2.71828183e+00 2.00855369e+01 5.45981500e+01]
 [7.38905610e+00 4.03428793e+02 4.03428793e+02]
 [2.00855369e+01 2.98095799e+03 7.38905610e+00]]


In [64]:
# sine function on matrix 
A=np.array([[0,90,30],[20, 45,0],[7, 60,75]])
print("A:")
print(A)
e=np.sin(A*np.pi/180)
print('sin of A:')
print(e)

A:
[[ 0 90 30]
 [20 45  0]
 [ 7 60 75]]
sin of A:
[[0.         1.         0.5       ]
 [0.34202014 0.70710678 0.        ]
 [0.12186934 0.8660254  0.96592583]]


In [65]:
# sigmoid function on matrix
# f(x)=sigma(x)=1/(1+e^-x) # it is activation function which do the output of any linaer equatin function for any value  between 0 and 1  and avoid negative output which is nonsense(inappropiate) in macine leaning.
A=np.array([[0.7,0.4,0.2],[1,0.6,1.5],[0.3,0.25,1.2]])
print("A: ")
print(A)
z=1/(1+np.exp(-A))# sigmoid function
print('z: ')
print(z)




A: 
[[0.7  0.4  0.2 ]
 [1.   0.6  1.5 ]
 [0.3  0.25 1.2 ]]
z: 
[[0.66818777 0.59868766 0.549834  ]
 [0.73105858 0.64565631 0.81757448]
 [0.57444252 0.5621765  0.76852478]]
